import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const dm_sans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });
const integralCF = localFont({
  src: './../fonts/IntegralCF-Regular.woff2',
  display: 'swap',
  variable: '--font-mono',
});
export const metadata: Metadata = {
  title: 'NFters',
  description: 'Generated by Jubayer-cmd',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${integralCF.variable} ${dm_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
